// =============================================================================
// AUTH ACTION TYPES
// =============================================================================
// TODO: group these better at some point

var AUTH_LOGIN_REQUEST  = 'AUTH_LOGIN_REQUEST';
var AUTH_LOGIN_SUCCESS  = 'AUTH_LOGIN_SUCCESS';
var AUTH_LOGIN_FAILURE  = 'AUTH_LOGIN_FAILURE';
var AUTH_LOGOUT         = 'AUTH_LOGOUT';

// forgot password flow - half implemented
var AUTH_FORGOT_PASSWORD_REQUEST = 'AUTH_FORGOT_PASSWORD_REQUEST';
var AUTH_FORGOT_PASSWORD_SUCCESS = 'AUTH_FORGOT_PASSWORD_SUCCESS';
var AUTH_FORGOT_PASSWORD_FAILURE = 'AUTH_FORGOT_PASSWORD_FAILURE';

// reset - not wired to any component yet
var AUTH_RESET_PASSWORD_REQUEST  = 'AUTH_RESET_PASSWORD_REQUEST';
var AUTH_RESET_PASSWORD_SUCCESS  = 'AUTH_RESET_PASSWORD_SUCCESS';
var AUTH_RESET_PASSWORD_FAILURE  = 'AUTH_RESET_PASSWORD_FAILURE';

var AUTH_TOKEN_REFRESH_REQUEST   = 'AUTH_TOKEN_REFRESH_REQUEST';
var AUTH_TOKEN_REFRESH_SUCCESS   = 'AUTH_TOKEN_REFRESH_SUCCESS';
var AUTH_TOKEN_REFRESH_FAILURE   = 'AUTH_TOKEN_REFRESH_FAILURE';

var AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';
var AUTH_SET_REDIRECT = 'AUTH_SET_REDIRECT';

// =============================================================================
// PRODUCT ACTION TYPES
// =============================================================================

var FETCH_PRODUCTS_REQUEST  = 'FETCH_PRODUCTS_REQUEST';
var FETCH_PRODUCTS_SUCCESS  = 'FETCH_PRODUCTS_SUCCESS';
var FETCH_PRODUCTS_FAILURE  = 'FETCH_PRODUCTS_FAILURE';

var FETCH_PRODUCT_REQUEST   = 'FETCH_PRODUCT_REQUEST';
var FETCH_PRODUCT_SUCCESS   = 'FETCH_PRODUCT_SUCCESS';
var FETCH_PRODUCT_FAILURE   = 'FETCH_PRODUCT_FAILURE';

var CREATE_PRODUCT_REQUEST  = 'CREATE_PRODUCT_REQUEST';
var CREATE_PRODUCT_SUCCESS  = 'CREATE_PRODUCT_SUCCESS';
var CREATE_PRODUCT_FAILURE  = 'CREATE_PRODUCT_FAILURE';

var UPDATE_PRODUCT_REQUEST  = 'UPDATE_PRODUCT_REQUEST';
var UPDATE_PRODUCT_SUCCESS  = 'UPDATE_PRODUCT_SUCCESS';
var UPDATE_PRODUCT_FAILURE  = 'UPDATE_PRODUCT_FAILURE';

var DELETE_PRODUCT_REQUEST  = 'DELETE_PRODUCT_REQUEST';
var DELETE_PRODUCT_SUCCESS  = 'DELETE_PRODUCT_SUCCESS';
var DELETE_PRODUCT_FAILURE  = 'DELETE_PRODUCT_FAILURE';

// categories
var FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
var FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
var FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

var SET_ACTIVE_CATEGORY     = 'SET_ACTIVE_CATEGORY';
var SET_PRODUCT_FILTER      = 'SET_PRODUCT_FILTER';
var SET_PRODUCT_SORT        = 'SET_PRODUCT_SORT';
var SET_PRODUCT_SEARCH      = 'SET_PRODUCT_SEARCH';
var CLEAR_PRODUCT_FILTERS   = 'CLEAR_PRODUCT_FILTERS';

// product editing
var SET_EDITING_PRODUCT     = 'SET_EDITING_PRODUCT';
var CLEAR_EDITING_PRODUCT   = 'CLEAR_EDITING_PRODUCT';
var UPDATE_EDITING_PRODUCT_FIELD = 'UPDATE_EDITING_PRODUCT_FIELD';

// bulk actions - TODO: implement these properly
var BULK_SELECT_PRODUCT     = 'BULK_SELECT_PRODUCT';
var BULK_DESELECT_PRODUCT   = 'BULK_DESELECT_PRODUCT';
var BULK_SELECT_ALL         = 'BULK_SELECT_ALL';
var BULK_DESELECT_ALL       = 'BULK_DESELECT_ALL';
var BULK_DELETE_REQUEST     = 'BULK_DELETE_REQUEST';
var BULK_DELETE_SUCCESS     = 'BULK_DELETE_SUCCESS';
var BULK_DELETE_FAILURE     = 'BULK_DELETE_FAILURE';

// inventory
var FETCH_INVENTORY_REQUEST  = 'FETCH_INVENTORY_REQUEST';
var FETCH_INVENTORY_SUCCESS  = 'FETCH_INVENTORY_SUCCESS';
var FETCH_INVENTORY_FAILURE  = 'FETCH_INVENTORY_FAILURE';
var UPDATE_INVENTORY_REQUEST = 'UPDATE_INVENTORY_REQUEST';
var UPDATE_INVENTORY_SUCCESS = 'UPDATE_INVENTORY_SUCCESS';
var UPDATE_INVENTORY_FAILURE = 'UPDATE_INVENTORY_FAILURE';

// pricing - added by Bob in Q2 2022
var UPDATE_PRICE_REQUEST     = 'UPDATE_PRICE_REQUEST';
var UPDATE_PRICE_SUCCESS     = 'UPDATE_PRICE_SUCCESS';
var UPDATE_PRICE_FAILURE     = 'UPDATE_PRICE_FAILURE';
var APPLY_DISCOUNT_REQUEST   = 'APPLY_DISCOUNT_REQUEST';
var APPLY_DISCOUNT_SUCCESS   = 'APPLY_DISCOUNT_SUCCESS';
var APPLY_DISCOUNT_FAILURE   = 'APPLY_DISCOUNT_FAILURE';

// =============================================================================
// USER ACTION TYPES
// =============================================================================

var FETCH_USERS_REQUEST     = 'FETCH_USERS_REQUEST';
var FETCH_USERS_SUCCESS     = 'FETCH_USERS_SUCCESS';
var FETCH_USERS_FAILURE     = 'FETCH_USERS_FAILURE';

var FETCH_USER_REQUEST      = 'FETCH_USER_REQUEST';
var FETCH_USER_SUCCESS      = 'FETCH_USER_SUCCESS';
var FETCH_USER_FAILURE      = 'FETCH_USER_FAILURE';

var CREATE_USER_REQUEST     = 'CREATE_USER_REQUEST';
var CREATE_USER_SUCCESS     = 'CREATE_USER_SUCCESS';
var CREATE_USER_FAILURE     = 'CREATE_USER_FAILURE';

var UPDATE_USER_REQUEST     = 'UPDATE_USER_REQUEST';
var UPDATE_USER_SUCCESS     = 'UPDATE_USER_SUCCESS';
var UPDATE_USER_FAILURE     = 'UPDATE_USER_FAILURE';

var DELETE_USER_REQUEST     = 'DELETE_USER_REQUEST';
var DELETE_USER_SUCCESS     = 'DELETE_USER_SUCCESS';
var DELETE_USER_FAILURE     = 'DELETE_USER_FAILURE';

// user roles
var FETCH_ROLES_REQUEST     = 'FETCH_ROLES_REQUEST';
var FETCH_ROLES_SUCCESS     = 'FETCH_ROLES_SUCCESS';
var FETCH_ROLES_FAILURE     = 'FETCH_ROLES_FAILURE';

var ASSIGN_ROLE_REQUEST     = 'ASSIGN_ROLE_REQUEST';
var ASSIGN_ROLE_SUCCESS     = 'ASSIGN_ROLE_SUCCESS';
var ASSIGN_ROLE_FAILURE     = 'ASSIGN_ROLE_FAILURE';

// user filters/search
var SET_USER_FILTER         = 'SET_USER_FILTER';
var SET_USER_SEARCH         = 'SET_USER_SEARCH';
var CLEAR_USER_FILTERS      = 'CLEAR_USER_FILTERS';
var SET_EDITING_USER        = 'SET_EDITING_USER';
var CLEAR_EDITING_USER      = 'CLEAR_EDITING_USER';

// profile - mixed in with user actions because someone was lazy
var FETCH_PROFILE_REQUEST   = 'FETCH_PROFILE_REQUEST';
var FETCH_PROFILE_SUCCESS   = 'FETCH_PROFILE_SUCCESS';
var FETCH_PROFILE_FAILURE   = 'FETCH_PROFILE_FAILURE';
var UPDATE_PROFILE_REQUEST  = 'UPDATE_PROFILE_REQUEST';
var UPDATE_PROFILE_SUCCESS  = 'UPDATE_PROFILE_SUCCESS';
var UPDATE_PROFILE_FAILURE  = 'UPDATE_PROFILE_FAILURE';

// =============================================================================
// UI ACTION TYPES
// =============================================================================

var TOGGLE_SIDEBAR          = 'TOGGLE_SIDEBAR';
var SET_SIDEBAR_OPEN        = 'SET_SIDEBAR_OPEN';
var SET_ACTIVE_TAB          = 'SET_ACTIVE_TAB';
var SHOW_MODAL              = 'SHOW_MODAL';
var HIDE_MODAL              = 'HIDE_MODAL';
var SHOW_NOTIFICATION       = 'SHOW_NOTIFICATION';
var HIDE_NOTIFICATION       = 'HIDE_NOTIFICATION';
var SET_LOADING             = 'SET_LOADING';
var CLEAR_LOADING           = 'CLEAR_LOADING';
var SET_GLOBAL_ERROR        = 'SET_GLOBAL_ERROR';
var CLEAR_GLOBAL_ERROR      = 'CLEAR_GLOBAL_ERROR';

// table sorting - duplicated between products and users, FIXME
var SET_TABLE_SORT          = 'SET_TABLE_SORT';
var SET_TABLE_PAGE          = 'SET_TABLE_PAGE';
var SET_TABLE_PAGE_SIZE     = 'SET_TABLE_PAGE_SIZE';

// =============================================================================
// REPORT ACTION TYPES (never finished - dead code)
// =============================================================================

// var FETCH_REPORT_REQUEST    = 'FETCH_REPORT_REQUEST';
// var FETCH_REPORT_SUCCESS    = 'FETCH_REPORT_SUCCESS';
// var FETCH_REPORT_FAILURE    = 'FETCH_REPORT_FAILURE';
// var EXPORT_CSV_REQUEST      = 'EXPORT_CSV_REQUEST';
// var EXPORT_CSV_SUCCESS      = 'EXPORT_CSV_SUCCESS';

module.exports = {
  // auth
  AUTH_LOGIN_REQUEST, AUTH_LOGIN_SUCCESS, AUTH_LOGIN_FAILURE, AUTH_LOGOUT,
  AUTH_FORGOT_PASSWORD_REQUEST, AUTH_FORGOT_PASSWORD_SUCCESS, AUTH_FORGOT_PASSWORD_FAILURE,
  AUTH_RESET_PASSWORD_REQUEST, AUTH_RESET_PASSWORD_SUCCESS, AUTH_RESET_PASSWORD_FAILURE,
  AUTH_TOKEN_REFRESH_REQUEST, AUTH_TOKEN_REFRESH_SUCCESS, AUTH_TOKEN_REFRESH_FAILURE,
  AUTH_CLEAR_ERROR, AUTH_SET_REDIRECT,

  // products
  FETCH_PRODUCTS_REQUEST, FETCH_PRODUCTS_SUCCESS, FETCH_PRODUCTS_FAILURE,
  FETCH_PRODUCT_REQUEST, FETCH_PRODUCT_SUCCESS, FETCH_PRODUCT_FAILURE,
  CREATE_PRODUCT_REQUEST, CREATE_PRODUCT_SUCCESS, CREATE_PRODUCT_FAILURE,
  UPDATE_PRODUCT_REQUEST, UPDATE_PRODUCT_SUCCESS, UPDATE_PRODUCT_FAILURE,
  DELETE_PRODUCT_REQUEST, DELETE_PRODUCT_SUCCESS, DELETE_PRODUCT_FAILURE,
  FETCH_CATEGORIES_REQUEST, FETCH_CATEGORIES_SUCCESS, FETCH_CATEGORIES_FAILURE,
  SET_ACTIVE_CATEGORY, SET_PRODUCT_FILTER, SET_PRODUCT_SORT,
  SET_PRODUCT_SEARCH, CLEAR_PRODUCT_FILTERS,
  SET_EDITING_PRODUCT, CLEAR_EDITING_PRODUCT, UPDATE_EDITING_PRODUCT_FIELD,
  BULK_SELECT_PRODUCT, BULK_DESELECT_PRODUCT, BULK_SELECT_ALL, BULK_DESELECT_ALL,
  BULK_DELETE_REQUEST, BULK_DELETE_SUCCESS, BULK_DELETE_FAILURE,
  FETCH_INVENTORY_REQUEST, FETCH_INVENTORY_SUCCESS, FETCH_INVENTORY_FAILURE,
  UPDATE_INVENTORY_REQUEST, UPDATE_INVENTORY_SUCCESS, UPDATE_INVENTORY_FAILURE,
  UPDATE_PRICE_REQUEST, UPDATE_PRICE_SUCCESS, UPDATE_PRICE_FAILURE,
  APPLY_DISCOUNT_REQUEST, APPLY_DISCOUNT_SUCCESS, APPLY_DISCOUNT_FAILURE,

  // users
  FETCH_USERS_REQUEST, FETCH_USERS_SUCCESS, FETCH_USERS_FAILURE,
  FETCH_USER_REQUEST, FETCH_USER_SUCCESS, FETCH_USER_FAILURE,
  CREATE_USER_REQUEST, CREATE_USER_SUCCESS, CREATE_USER_FAILURE,
  UPDATE_USER_REQUEST, UPDATE_USER_SUCCESS, UPDATE_USER_FAILURE,
  DELETE_USER_REQUEST, DELETE_USER_SUCCESS, DELETE_USER_FAILURE,
  FETCH_ROLES_REQUEST, FETCH_ROLES_SUCCESS, FETCH_ROLES_FAILURE,
  ASSIGN_ROLE_REQUEST, ASSIGN_ROLE_SUCCESS, ASSIGN_ROLE_FAILURE,
  SET_USER_FILTER, SET_USER_SEARCH, CLEAR_USER_FILTERS,
  SET_EDITING_USER, CLEAR_EDITING_USER,
  FETCH_PROFILE_REQUEST, FETCH_PROFILE_SUCCESS, FETCH_PROFILE_FAILURE,
  UPDATE_PROFILE_REQUEST, UPDATE_PROFILE_SUCCESS, UPDATE_PROFILE_FAILURE,

  // ui
  TOGGLE_SIDEBAR, SET_SIDEBAR_OPEN, SET_ACTIVE_TAB,
  SHOW_MODAL, HIDE_MODAL,
  SHOW_NOTIFICATION, HIDE_NOTIFICATION,
  SET_LOADING, CLEAR_LOADING,
  SET_GLOBAL_ERROR, CLEAR_GLOBAL_ERROR,
  SET_TABLE_SORT, SET_TABLE_PAGE, SET_TABLE_PAGE_SIZE
};
